export const ResList = [
      {   
          id: 4827,
          restaurant_name: "McDonald's",
          restaurant_place: "Delhi",
          cuisine: "American, Fast Food",
          food_image_url: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/336fe848fa16c04d15ab144e994f5309",
          property: "popular",
          rating: 2.2,
          delivery_time: "30-35 mins",
          veg: true,
          promoted: true
        },
        {
          id: 4828,
          restaurant_name: "KFC",
          restaurant_place: "Panipat",
          cuisine: "American, Fried Chicken",
          food_image_url: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/zqnxmdpcoxzi4ovasud8",
          property: "featured",
          rating: 3.1,
          delivery_time: "35-40 mins",
          veg: false,
          promoted: false,
        },
        {
            id: 4829,
          restaurant_name: "The Good Bowl",
          restaurant_place: "Sector 25",
          cuisine: "Biryani, Pastas, Punjabi, Desserts",
          food_image_url: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/2a82a8fab59d21750bad47426c50188a",
          property: "new",
          rating: 4.5,
          delivery_time: "25-30 mins",
          veg: true,
          promoted: false,
        },
        {
            id: 4830,
          restaurant_name: "Kwality Walls",
          restaurant_place: "Old HB Colony",
          cuisine: "Ice Cream",
          food_image_url: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2025/3/27/e6c7c779-c608-4c42-802b-ae0f8a23a657_1069341.jpg",
          property: "popular",
          rating: 4.0,
          delivery_time: "20-25 mins",
          veg: true,
          promoted: false,
        },
        {
            id: 4831,
          restaurant_name: "Atithi Dhaba",
          restaurant_place: "Sector 25",
          cuisine: "Indian, Beverages & Salads",
          food_image_url: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/uq2f0savptdsmhrjs3lz",
          property: "budget",
          rating: 4.3,
          delivery_time: "40-45 mins",
          veg: true,
          promoted: false,
        },
        {
            id: 4832,
            restaurant_name: "The Fusion Lounge",
            restaurant_place: "Railway Station",
            cuisine: "South Indian",
            food_image_url: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/fa4944f0cfdcbca2bec1f3ab8e3db3f7",
            property: "budget",
            rating: 4.2,
            delivery_time: "70-75 mins",
            veg: true, 
            promoted: false, 
        },
        {
            id: 4833,
            restaurant_name: "The Indian Coffee House",
            restaurant_place: "khajiri Chowk",
            cuisine: "South Indian, Fast Food",
            food_image_url: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/2469fa88ee9b0b5d1366ba88f2a7fa7f",
            property: "budget",
            rating: 4.6,
            delivery_time: "50-55 mins",
            veg: true, 
            promoted: false,  
        },
        {
            id: 4834,
            restaurant_name: "New Rahdey Shyam Choule Bhutere",
            restaurant_place: "Mohan Nagar",
            cuisine: "Indian Snacks",
            food_image_url: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/0adf25c57357161b20c11281d8a443e6",
            property: "budget",
            rating: 5.0,
            delivery_time: "65-65 mins",
            veg: true, 
            promoted: true
        },
        {
            id: 4835,
            restaurant_name: "Bihar Champion Litti Chokha ",
            restaurant_place: "Mohan Nagar",
            cuisine: "Bihari North Indian",
            food_image_url: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/79c9b82c646f5c469503e07014a05031",
            property: "budget",
            rating: 5.0,
            delivery_time: "50-55 mins",
            veg: true,  
            promoted: false,
        },
        {
            id: 4836,
            restaurant_name: "Join Food for you",
            restaurant_place: "Saket Place",
            cuisine: 'North Indian',
            food_image_url: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/e2hpvt6o23msw0ibtuqv",
            property: "budget",
            rating: 3.8,
            delivery_time: "65-65 mins",
            veg: true, 
            promoted: false, 
        },
        {
            id: 4837,
            restaurant_name: "Join Food for you",
            restaurant_place: "Saket Place",
            cuisine: 'North Indian',
            food_image_url: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/smo2yv6budwe0ciye1ry",
            property: "budget",
            rating: 3.8,
            delivery_time: "35-45 mins",
            veg: true, 
            promoted: true, 
        },
        {
            id: 4838,
            restaurant_name: "Famous Dum biryani",
            restaurant_place: "Saket Place",
            cuisine: 'North Indian',
            food_image_url: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/f594f4f63d3e00e93203f02d40e38d24",
            property: "budget",
            rating: 2.8,
            delivery_time: "45-55 mins",
            veg: false,  
            promoted: false,
        },
        {
            id: 4839,
            restaurant_name: "The Calzones",
            restaurant_place: "Captain Nagar",
            cuisine: 'North Indian, Kebabs',
            food_image_url: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/6/20/34735552-7831-4d47-8657-b7b8c9c5dc86_880795.jpg",
            property: "budget",
            rating: 3.9,
            delivery_time: "30-35 mins",
            veg: false,  
            promoted: false,
        },
        {
            id: 4840,
            restaurant_name: "Master Chef",
            restaurant_place: "Captain Nagar",
            cuisine: 'Chinese',
            food_image_url: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/12/23/d2ac27f7-bead-480e-9921-5027794bce9b_1013479.jpg",
            property: "budget",
            rating: 3.9,
            delivery_time: "20-25 mins",
            veg: false, 
            promoted: false, 
        },
        {
            id: 4841,
            restaurant_name: "D'Olives - The Cardamom Kitchen",
            restaurant_place: "Bus Stand",
            cuisine: 'Biryani',
            food_image_url: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/xak6tgmheghlielzqiz5",
            property: "budget",
            rating: 4.1,
            delivery_time: "10-15 mins",
            veg: false,
            promoted: false,  
        },
        {
            id: 4842,
            restaurant_name: "Taneja chicken corner",
            restaurant_place: "Sanoli Road",
            cuisine: 'Tandoor, Punjabi',
            food_image_url: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/qeb7klr9kadmb7hbjlfq",
            property: "budget",
            rating: 3.8,
            delivery_time: "30-35 mins",
            veg: false, 
            promoted: false, 
        },

  ]


 
//   ==========================================================================================
